---

- name: Install exim4
  include_tasks: 
    file: install.yml
    apply:
      tags: ['exim4-sendonly-install']

- name: Configure exim4
  include_tasks:
    file: configure.yml
    apply:
      tags: ['exim4-sendonly-configure']

- name: Setup aws ses
  include_tasks:
    file: aws_ses.yml
    apply:
      tags: ['exim4-sendonly-configure']
  when: exim4_aws_access_key_id != '' and exim4_aws_secret_access_key != ''
  

- name: Start exim4
  service:
    name: exim4
    state: started
    enabled: true
  changed_when: false
  tags: ['always']